'use strict';
(() => {
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const tr=text=>window.I18n.translate(text), isSw=()=>window.I18n.language==='sw';
const data=window.SHOP_DATA, products=data.products, media=data.media, config=data.config;
const byId=new Map(products.map(p=>[p.id,p])), byMedia=new Map(media.map(m=>[m.id,m]));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=n=>new Intl.NumberFormat('en-TZ').format(n), money=n=>n==null?'Ask for price':'TSh '+number(n);
const ramText=p=>p.ram==null?'Confirm RAM':p.ram+'GB RAM';
const summary=p=>p.summary||[ramText(p),p.storage];
const specs=p=>p.specs||[{label:'Processor',value:p.cpu},{label:'Memory',value:ramText(p)},{label:'Storage',value:p.storage},{label:'Display',value:p.screen},...(p.features.length?[{label:'Features',value:p.features.join(' · ')}]:[])];
const icons={search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',moon:'<path d="M20.8 13A9 9 0 0 1 11 3.2 9 9 0 1 0 20.8 13Z"/>',sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5"/>',heart:'<path d="M20.8 4.7a5.5 5.5 0 0 0-7.8 0L12 5.8l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.5a5.5 5.5 0 0 0 0-7.8Z"/>',bag:'<path d="M5 7h14l1 14H4L5 7Z"/><path d="M9 8V6a3 3 0 0 1 6 0v2"/>',phone:'<path d="m5 3 4 1 1 5-3 2c1.4 3 3 4.6 6 6l2-3 5 1 1 4c-1 3-5 3-9 1S4 14 2 9 2 4 5 3Z"/>',whatsapp:'<path d="M21 11.6a9 9 0 0 1-13.5 7.8L3 21l1.5-4.6A9 9 0 1 1 21 11.6Z"/><path d="m8 7 2 3-1 1c1 2 2 3 4 3l1-1 3 1c0 3-3 3-6 1S6 9 8 7Z"/>',instagram:'<rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r=".8" fill="currentColor" stroke="none"/>',wallet:'<path d="M20 8V5H5a2 2 0 0 0-2 2v12h17V8H5a2 2 0 0 1 0-4l12-2v3"/><path d="M16 11h6v5h-6z"/>',image:'<rect x="3" y="3" width="18" height="18" rx="3"/><circle cx="8" cy="8" r="1.5"/><path d="m21 15-6-6-7 8-3-3-2 2"/>',play:'<path d="m8 5 11 7-11 7Z"/>',compare:'<path d="M7 3v18m10-18v18M4 7l3-4 3 4m4 10 3 4 3-4M2 12h20"/>',cpu:'<rect x="6" y="6" width="12" height="12" rx="2"/><path d="M9 9h6v6H9zM9 2v4m6-4v4M9 18v4m6-4v4M2 9h4m-4 6h4m12-6h4m-4 6h4"/>',laptop:'<rect x="4" y="3" width="16" height="13" rx="2"/><path d="M4 16 1 21h22l-3-5M9 19h6"/>',tablet:'<rect x="4" y="2" width="16" height="20" rx="2"/><path d="M11 19h2"/>',message:'<path d="M21 11a8 8 0 0 1-8 8H7l-4 3V5a3 3 0 0 1 3-3h7a8 8 0 0 1 8 9Z"/><path d="M7 8h9M7 12h6"/>',filter:'<path d="M3 6h18M3 12h18M3 18h18"/><circle cx="8" cy="6" r="2" fill="currentColor"/><circle cx="16" cy="12" r="2" fill="currentColor"/><circle cx="9" cy="18" r="2" fill="currentColor"/>',x:'<path d="m6 6 12 12M6 18 18 6"/>',left:'<path d="m15 5-7 7 7 7"/>',right:'<path d="m9 5 7 7-7 7"/>'};
const icon=n=>`<svg viewBox="0 0 24 24" aria-hidden="true">${icons[n]||icons.laptop}</svg>`;
function paintIcons(root=document){root.querySelectorAll('[data-icon]').forEach(el=>{el.innerHTML=icon(el.dataset.icon);});}
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem('apex-computers-'+key)??localStorage.getItem('isaac-tech-'+key))??fallback;}catch{return fallback;}};
function persist(key,val){try{localStorage.setItem('apex-computers-'+key,JSON.stringify(val));}catch{/* Storage may be unavailable in private/offline browsers. */}}
let saved=read('saved',[]);saved=Array.isArray(saved)?saved.filter(id=>byId.has(id)):[];
let bag=read('bag',[]);bag=Array.isArray(bag)?bag.filter(x=>x&&byId.has(x.id)&&Number.isInteger(x.qty)&&x.qty>=1&&x.qty<=10&&Number.isInteger(x.variant)&&x.variant>=0&&x.variant<Math.max(1,byId.get(x.id).variants.length)).slice(0,20):[];
let compare=[], state={category:'All',brand:'',budget:'',ram:'',sort:'featured',query:'',saved:false,limit:12};
let galleryLimit=8,galleryView=[],viewer=[],viewerIndex=0,currentProduct=null,currentVariant=0,toastTimer;
const wa=text=>'https://wa.me/'+config.phone+'?text='+encodeURIComponent(text);
const sms=text=>'sms:+'+config.phone+'?body='+encodeURIComponent(text);
function productLine(p,v=0){const opt=p.variants[v];return `${p.name}${opt?' — '+tr(opt.label):''} | ${tr(money(opt?.price??p.price))}`;}
function productMessage(p,v=0,intent='ask'){
 const intro=isSw()?(intent==='buy'?'Habari Apex Computers, ningependa kuagiza ':'Habari Apex Computers, naomba kuulizia '):(intent==='buy'?'Hi Apex Computers, I would like to order ':'Hi Apex Computers, I’m interested in ');
 const ending=isSw()?'. Tafadhali thibitisha bei ya sasa, upatikanaji, hali na sifa kamili. Tujadiliane kuhusu malipo na kuchukua au kuletewa bidhaa.':'. Please confirm today’s price, availability, condition and exact specifications, then advise payment and collection/delivery.';
 return intro+productLine(p,v)+ending;
}
const productWa=(p,v=0,intent='ask')=>wa(productMessage(p,v,intent));
const productSms=(p,v=0,intent='ask')=>sms(productMessage(p,v,intent));
function updateGeneralContacts(){const message=isSw()?'Habari Apex Computers, naomba msaada kuchagua bidhaa. Bajeti yangu ni TSh ___ na matumizi yangu ni ___.':'Hi Apex Computers, please help me choose a product. My budget is TSh ___ and I need it for ___.';document.querySelectorAll('[data-wa="help"]').forEach(a=>a.href=wa(message));document.querySelectorAll('[data-sms="help"]').forEach(a=>a.href=sms(message));}

function toast(msg){$('#toast').textContent=msg;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3200);}
function applyTheme(theme){document.documentElement.dataset.theme=theme;$('#theme-toggle').innerHTML=icon(theme==='dark'?'sun':'moon');$('#theme-toggle').setAttribute('aria-label','Switch to '+(theme==='dark'?'light':'dark')+' mode');persist('theme',theme);}
paintIcons();applyTheme(read('theme','light')==='dark'?'dark':'light');$('#theme-toggle').onclick=()=>applyTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');
$('#hero-image').src=byMedia.get(byId.get('p23').image).src;$('#year').textContent=new Date().getFullYear();
const primaryNav=$$('.desktop-nav [data-nav],.mobile-nav [data-nav]');
function syncPrimaryNav(){let current='shop';for(const id of ['contact','shop','flyers','help']){const section=$('#'+id);if(section&&section.getBoundingClientRect().top<=Math.max(210,innerHeight*.34))current=id;}primaryNav.forEach(link=>{const active=link.dataset.nav===current;link.classList.toggle('active',active);if(active)link.setAttribute('aria-current','location');else link.removeAttribute('aria-current');});}
let navFrame=0;addEventListener('scroll',()=>{$('#header').classList.toggle('scrolled',scrollY>24);if(!navFrame)navFrame=requestAnimationFrame(()=>{navFrame=0;syncPrimaryNav();});},{passive:true});syncPrimaryNav();
function syncBag(){persist('bag',bag);$$('.bag-count').forEach(el=>el.textContent=bag.reduce((n,x)=>n+x.qty,0));}
function getImage(p){return byMedia.get(p.image);}
function card(p){const m=getImage(p),isSaved=saved.includes(p.id),cash=p.features.includes('Cash deal only'),nonTouch=p.features.some(x=>x.startsWith('Non-touch'));return `<article class="product-card"><div class="product-image"><button class="image-open ${esc(m?.kind)}" data-product="${p.id}" aria-label="View ${esc(p.name)}">${m?`<img src="${m.thumb}" alt="${esc(p.name)} ${m.kind==='flyer'?'original flyer':m.kind==='render'?'illustrative render':m.kind==='video'?'supplied product video':'product photo'}" width="480" height="480" loading="lazy">${m.kind==='video'?`<span class="video-badge">${icon('play')} Video</span>`:''}`:icon('laptop')}</button><span class="product-tag">${esc(p.category.toUpperCase())}</span>${cash||nonTouch?`<span class="deal-badges" aria-label="${cash?'Cash only. ':''}${nonTouch?'Non-touch display.':''}">${cash?'<span class="deal-badge cash">CASH ONLY</span>':''}${nonTouch?'<span class="deal-badge non-touch">NON-TOUCH</span>':''}</span>`:''}<button class="save-btn ${isSaved?'selected':''}" data-save="${p.id}" aria-label="${isSaved?'Unsave':'Save'} ${esc(p.name)}" aria-pressed="${isSaved}">${icon('heart')}</button></div><div class="product-body"><div class="product-brand">${esc(p.brand)}</div><button class="product-name" data-product="${p.id}">${esc(p.name)}</button><p class="product-cpu">${esc(p.cpu)}</p><div class="spec-chips">${summary(p).map(x=>`<span>${esc(x)}</span>`).join('')}</div><div class="price-label">${p.variants.length?'From · ':''}Price from your supplied listing · Confirm today</div><div class="product-price">${p.price==null?'Ask for price':'<small>TSh</small> '+number(p.price)}</div><div class="card-actions">${p.variants.length>1?`<button class="button whatsapp" data-product="${p.id}">${icon('whatsapp')}<span>Buy</span></button>`:`<a class="button whatsapp" href="${esc(productWa(p,0,'buy'))}" target="_blank" rel="noopener" aria-label="Buy ${esc(p.name)} on WhatsApp">${icon('whatsapp')}<span>Buy</span></a>`}<button class="button outline" data-enquire="${p.id}">Enquire</button></div><button class="product-details-link" data-product="${p.id}">Details <span>↗</span></button><label class="compare-check"><input type="checkbox" data-compare="${p.id}" ${compare.includes(p.id)?'checked':''}> Compare product</label></div></article>`;}
function filtered(){let rows=products.filter(p=>(state.category==='All'||p.category===state.category)&&(!state.brand||p.brand===state.brand)&&(!state.saved||saved.includes(p.id))&&(!state.ram||p.ram>=Number(state.ram))&&(!state.budget||(p.price!=null&&(state.budget==='over'?p.price>1500000:p.price<=Number(state.budget)))));const words=state.query.toLowerCase().trim().split(/\s+/).filter(Boolean);rows=rows.filter(p=>words.every(w=>[p.name,p.cpu,p.ram+'GB',p.storage,p.category,tr(p.category),p.screen,...p.features,...p.features.map(tr)].join(' ').toLowerCase().includes(w)));const rank=p=>{const i=config.featured.indexOf(p.id);return i===-1?999:i;};rows.sort((a,b)=>state.sort==='low'?(a.price??Infinity)-(b.price??Infinity):state.sort==='high'?(b.price??-1)-(a.price??-1):state.sort==='ram'?b.ram-a.ram:state.sort==='name'?a.name.localeCompare(b.name):rank(a)-rank(b));return rows;}
function renderProducts(){const rows=filtered();$('#results-count').textContent=(state.saved?'Saved · ':'')+`${rows.length} ${rows.length===1?'product':'products'}${state.query?' matching “'+state.query+'”':''}`;$('#product-grid').innerHTML=rows.length?rows.slice(0,state.limit).map(card).join(''):`<div class="empty-state"><h3>${state.saved?'Your favourites live here.':'No matches just yet.'}</h3><p>${state.saved?'Tap the heart on a laptop to save it.':'Try a different search or clear a filter.'}</p><button class="button outline" data-reset>Browse all laptops</button></div>`;$('#load-products').hidden=rows.length<=state.limit;$('#load-products').textContent=`Show more products (${Math.max(0,Math.min(12,rows.length-state.limit))} more)`;$$('#category-tabs button').forEach(b=>{const active=b.dataset.category===state.category;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});}
const categories=['All','Accessories','Business','Everyday','2-in-1','Workstation','Gaming','MacBook','All-in-one','Storage','Printers'];$('#category-tabs').innerHTML=categories.map(c=>`<button data-category="${c}" aria-pressed="${c==='All'}">${c==='All'?'All products':c}</button>`).join('');
$('#brand-filter').innerHTML+=[...new Set(products.map(p=>p.brand))].sort().map(b=>`<option>${esc(b)}</option>`).join('');
function reset(){state={...state,category:'All',brand:'',ram:'',budget:'',query:'',saved:false,limit:12};['brand-filter','ram-filter','budget-filter','search'].forEach(id=>$('#'+id).value='');renderProducts();}
$('#reset-filters').onclick=reset;$('#load-products').onclick=()=>{state.limit+=12;renderProducts();};
[['brand-filter','brand'],['budget-filter','budget'],['ram-filter','ram'],['sort','sort']].forEach(([id,key])=>$('#'+id).addEventListener('change',e=>{state[key]=e.target.value;state.limit=12;renderProducts();}));
$('#search').oninput=e=>{state.query=e.target.value;state.saved=false;state.limit=12;renderProducts();};
$('#search-form').onsubmit=e=>{e.preventDefault();$('#shop').scrollIntoView({behavior:'smooth'});};
function showSaved(){reset();state.saved=true;renderProducts();$('#shop').scrollIntoView({behavior:'smooth'});}
$('#saved-toggle').onclick=showSaved;$('#mobile-saved').onclick=showSaved;
function openDialog(id){const d=$('#'+id);if(!d.open)d.showModal();document.body.style.overflow='hidden';}
$$('dialog').forEach(d=>{d.addEventListener('close',()=>{if(!document.querySelector('dialog[open]'))document.body.style.overflow='';});d.addEventListener('click',e=>{if(e.target!==d)return;const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();});});
function openProduct(id,variant=0){const p=byId.get(id);if(!p)return;currentProduct=id;currentVariant=Number.isInteger(variant)&&variant>=0&&variant<Math.max(1,p.variants.length)?variant:0;renderProduct();openDialog('product-dialog');}
const mediaCaption=m=>m?.kind==='video'?'Supplied product video · Tap play to view the supplied unit':(m?.kind==='flyer'?'Original promotional flyer':m?.kind==='render'?'Illustrative product render':'Supplied product photo')+' · Confirm the exact unit';
const detailMedia=m=>m?.kind==='video'?`<video class="main-video" controls playsinline preload="metadata" poster="${esc(m.thumb)}" aria-label="${esc(m.title)}"><source src="${esc(m.src)}" type="${esc(m.mime||'video/mp4')}">Your browser cannot play this video.</video>`:`<button class="main-photo" data-media="${m?.id||''}"><img src="${m?.src||''}" alt="${esc(m?.title||'Product image')}" width="800" height="800"></button>`;
function renderProduct(){const p=byId.get(currentProduct),m=getImage(p),photos=[...new Set([p.image,...p.photos,p.flyer].filter(Boolean))].map(id=>byMedia.get(id)).filter(Boolean);$('#product-content').innerHTML=`<div class="product-detail"><div class="detail-media"><div class="detail-player" id="detail-player">${detailMedia(m)}</div><p class="photo-caption" id="detail-caption">${mediaCaption(m)}</p><div class="thumbnails">${photos.map(x=>`<button data-detail-photo="${x.id}" aria-label="View ${esc(x.title)}"><img src="${x.thumb}" alt="${esc(x.title)}" loading="lazy">${x.kind==='video'?`<span class="thumbnail-play">${icon('play')}</span>`:''}</button>`).join('')}</div></div><div class="detail-copy"><div class="product-brand">${esc(p.brand)} / ${esc(p.category)}</div><h2 id="detail-title">${esc(p.name)}</h2><div class="price-label">Price from your supplied listing · Confirm today</div><div class="product-price" id="detail-price">${money(p.variants[currentVariant]?.price??p.price)}</div>${p.variants.length?`<label class="variant-label">Choose your configuration<select id="product-variant">${p.variants.map((v,i)=>`<option value="${i}" ${i===currentVariant?'selected':''}>${esc(v.label)} — ${money(v.price)}</option>`).join('')}</select></label>`:''}<dl class="detail-specs">${specs(p).map(x=>`<dt>${esc(x.label)}</dt><dd>${esc(x.value)}</dd>`).join('')}</dl><p class="detail-note">${esc(p.note||'Ask for current stock photos, battery condition and the exact configuration. Delivery and warranty terms are agreed before payment.')}</p><div class="detail-message-options"><a class="button whatsapp wide" id="detail-wa" href="${esc(productWa(p,currentVariant,'buy'))}" target="_blank" rel="noopener">${icon('whatsapp')} <span>Buy on WhatsApp</span> <span>↗</span></a><a class="button outline wide" id="detail-sms" href="${esc(productSms(p,currentVariant,'buy'))}">${icon('message')} <span>Send by SMS</span> <span>↗</span></a></div><button class="button outline wide" data-enquire="${p.id}" data-selected="true">${icon('message')} <span>Send email enquiry</span></button><div class="detail-links"><button id="share-product">Share product ↗</button><button data-save="${p.id}">${saved.includes(p.id)?'♥ Saved':'♡ Save for later'}</button>${p.flyer?`<button data-media="${p.flyer}">View original flyer ↗</button>`:''}</div></div></div>`;
$('#share-product').onclick=async()=>{if(location.protocol==='file:'){toast('Publish the website to share product links.');return;}const url=new URL(location.href);url.hash='product='+encodeURIComponent(p.id)+'&variant='+currentVariant;try{if(navigator.share){await navigator.share({title:p.name,url:url.href});}else if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(url.href);toast('Product link copied');}else{location.hash=url.hash;toast('Copy the page address to share this product');}}catch(error){if(error.name!=='AbortError')toast('Copy the page address to share this product');}};
const sel=$('#product-variant');if(sel)sel.onchange=()=>{currentVariant=Number(sel.value);$('#detail-price').textContent=money(p.variants[currentVariant].price);$('#detail-wa').href=productWa(p,currentVariant,'buy');$('#detail-sms').href=productSms(p,currentVariant,'buy');};}
function addBag(id,variant=0){const p=byId.get(id);if(!p)return;const item=bag.find(x=>x.id===id&&x.variant===variant);if(item){if(item.qty>=10){toast('For more than 10 units, please contact Apex Computers.');return;}item.qty++;}else{if(bag.length>=20){toast('For a larger enquiry, please contact Apex Computers directly.');return;}bag.push({id,variant,qty:1});}syncBag();toast('Added to your enquiry bag');}
function bagText(){return (isSw()?'Habari Apex Computers, ningependa kuagiza bidhaa hizi. Naomba uthibitishe upatikanaji na bei za sasa:\n\n':'Hi Apex Computers, I would like to order these products. Please confirm availability and today’s prices:\n\n')+bag.map(x=>`${x.qty} × ${productLine(byId.get(x.id),x.variant)}`).join('\n')+(isSw()?'\n\nNaomba maelezo ya hali ya bidhaa, malipo na kuchukua au kuletewa.':'\n\nPlease share the condition, payment and collection/delivery details.');}
function startEnquiry(id,selected=false){
 const p=byId.get(id);if(!p)return;
 if(p.variants.length>1&&!selected){openProduct(id);return;}
 const variant=selected&&currentProduct===id?currentVariant:0;
 if(!bag.some(x=>x.id===id&&x.variant===variant))addBag(id,variant);
 if(!bag.some(x=>x.id===id&&x.variant===variant))return;
 $('#product-dialog').close();openBag();
}

function renderBag(){syncBag();$('#bag-checkout').hidden=!bag.length;$('#bag-items').innerHTML=bag.length?bag.map((x,i)=>{const p=byId.get(x.id),m=getImage(p),v=p.variants[x.variant];return `<article class="bag-item"><img src="${m?.thumb||''}" alt="${esc(p.name)}"><div class="bag-info"><h3>${esc(p.name)}</h3><p>${esc(v?.label||p.storage)}${p.specs?'':' · '+esc(ramText(p))}</p><strong>${money(v?.price??p.price)}</strong><div class="quantity"><button data-quantity="${i}" data-change="-1" aria-label="Reduce quantity for ${esc(p.name)}">−</button><span>${x.qty}</span><button data-quantity="${i}" data-change="1" aria-label="Increase quantity for ${esc(p.name)}">+</button></div></div><button class="remove-item" data-remove="${i}" aria-label="Remove ${esc(p.name)}">${icon('x')}</button></article>`;}).join(''):'<div class="empty-state"><h3>Room for your next upgrade.</h3><p>Add a laptop to ask about availability and price.</p><button class="button dark" data-close="bag-dialog">Keep exploring</button></div>';const total=bag.reduce((n,x)=>{const p=byId.get(x.id);return n+(p.variants[x.variant]?.price??p.price??0)*x.qty;},0);$('#bag-total').textContent=money(total)+(bag.some(x=>byId.get(x.id).price==null)?' + quote items':'');const message=bagText();$('#bag-whatsapp').href=wa(message);$('#bag-sms').href=sms(message);}
let emailConfig=null, widgetId=null, turnstileToken='';
function showEmailAvailability(){const el=$('#email-availability');el.textContent=location.protocol==='file:'?'Offline preview: email needs deployment. You can send your selection by WhatsApp or SMS.':emailConfig?.emailEnabled===false?'Email enquiries are not connected yet. Please use WhatsApp or SMS above.':'';}
async function setupEmail(){showEmailAvailability();if(location.protocol==='file:')return;if(emailConfig)return;try{const r=await fetch('/api/config');if(!r.ok)return;emailConfig=await r.json();showEmailAvailability();if(emailConfig.turnstileSiteKey){window.onApexTurnstile=()=>{widgetId=window.turnstile.render('#turnstile',{sitekey:emailConfig.turnstileSiteKey,callback:t=>{turnstileToken=t;},'expired-callback':()=>{turnstileToken='';},'error-callback':()=>{turnstileToken='';}});};const script=document.createElement('script');script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?onload=onApexTurnstile&render=explicit';script.async=true;document.head.appendChild(script);}}catch{/* WhatsApp stays available if the email endpoint is offline. */}}
function openBag(){renderBag();if(bag.length){$('#send-enquiry').hidden=false;$('#bag-whatsapp').hidden=false;$('#bag-sms').hidden=false;$('#form-status').textContent='';}openDialog('bag-dialog');setupEmail();}$('#bag-toggle').onclick=openBag;$('#mobile-bag').onclick=openBag;
$('#enquiry-form').onsubmit=async e=>{e.preventDefault();const form=e.target,status=$('#form-status'),button=$('#send-enquiry');status.className='';if(!bag.length)return;
const fields=Object.fromEntries(new FormData(form));
const issue=String(fields.name||'').trim().length<2?['name','Please enter your full name.']:!/^[-+\d()\s]{7,25}$/.test(fields.phone||'')||String(fields.phone).replace(/\D/g,'').length<7?['phone','Please enter a valid phone number.']:fields.email&&!/^[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+$/.test(fields.email)?['email','Please enter a valid email address.']:fields.consent!=='on'?['consent','Please tick the consent box.']:null;
if(issue){status.className='error';status.textContent=issue[1];form.elements[issue[0]].focus();return;}
if(location.protocol==='file:'){status.className='error';status.textContent='This is the offline preview. Email needs deployment; please use WhatsApp or SMS.';return;}if(emailConfig?.turnstileSiteKey&&!turnstileToken){status.className='error';status.textContent='Please complete the security check before sending.';return;}button.disabled=true;button.textContent='Sending…';try{const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),25000);let response;try{response=await fetch('/api/enquire',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...fields,language:window.I18n.language,consent:fields.consent==='on',items:bag.map(x=>({...x})),turnstileToken}),signal:controller.signal});}finally{clearTimeout(timeout);}const result=await response.json();if(!response.ok||!result.ok)throw new Error(result.message||'The enquiry could not be sent. Please use WhatsApp or SMS.');status.className='success';status.textContent=`Enquiry ${result.reference} sent. Apex Computers will contact you using the details you provided.`;form.reset();bag=[];syncBag();$('#bag-items').innerHTML='<p>Your enquiry has been sent. Thank you.</p>';$('#bag-total').textContent=money(0);$('#bag-whatsapp').hidden=true;$('#bag-sms').hidden=true;button.hidden=true;}catch(error){status.className='error';status.textContent=error.name==='AbortError'?'The connection timed out. Delivery is unconfirmed; please contact Apex Computers on WhatsApp or SMS before resending.':error.message?.includes('JSON')?'Email is unavailable here. Please use WhatsApp or SMS.':error.message||'Could not connect. Please use WhatsApp or SMS.';}finally{button.disabled=false;button.innerHTML='Send enquiry <span>↗</span>';if(window.turnstile&&widgetId!=null){window.turnstile.reset(widgetId);turnstileToken='';}}};
function updateCompare(){const tray=$('#compare-tray');tray.hidden=!compare.length;$('#compare-label').textContent=`${compare.length} of 3 selected`;$$('[data-compare]').forEach(el=>el.checked=compare.includes(el.dataset.compare));}
$('#compare-clear').onclick=()=>{compare=[];updateCompare();};
$('#compare-open').onclick=()=>{if(compare.length<2){toast('Select one more laptop to compare.');return;}const rows=compare.map(id=>byId.get(id));const cells=fn=>rows.map(p=>`<td>${fn(p)}</td>`).join('');$('#compare-content').innerHTML=`<div class="comparison-scroll"><table class="comparison-table"><thead><tr><th scope="col">Compare</th>${rows.map(p=>`<th scope="col"><img src="${getImage(p)?.thumb||''}" alt="${esc(p.name)}"><h3>${esc(p.name)}</h3></th>`).join('')}</tr></thead><tbody>${[['Supplied listing price',p=>money(p.price)+(p.variants.length?' · from':'')],['Processor / type',p=>esc(p.cpu)],['RAM',p=>p.specs?'Not applicable':p.ram==null?'Confirm RAM':p.ram+'GB'],['Storage / details',p=>p.specs?esc(p.specs.map(x=>x.label+': '+x.value).join(' · ')):esc(p.storage)],['Display',p=>esc(p.screen)],['Features',p=>esc(p.features.join(' · ')||'Confirm with Apex Computers')],['Configuration',p=>esc(p.variants.map(v=>v.label+': '+money(v.price)).join(' / ')||'As listed')],['Enquire',p=>`<a class="button dark" href="${esc(productWa(p))}" target="_blank" rel="noopener">Ask Apex Computers ↗</a>`]].map(([label,fn])=>`<tr><th scope="row">${label}</th>${cells(fn)}</tr>`).join('')}</tbody></table></div>`;openDialog('compare-dialog');};
function renderGallery(){const query=$('#gallery-search').value.trim().toLowerCase(),type=$('#gallery-type').value;galleryView=media.filter(m=>!m.archived&&(type==='all'||m.kind===type)&&(!query||(m.title+' '+m.original+' '+(m.searchText||'')).toLowerCase().includes(query)));$('#gallery-grid').innerHTML=galleryView.length?galleryView.slice(0,galleryLimit).map(m=>`<button class="gallery-card" data-media="${m.id}"><img src="${m.thumb}" alt="${esc(m.title)}" width="480" height="600" loading="lazy">${m.kind==='video'?`<span class="video-badge gallery-video-badge">${icon('play')} Video</span>`:''}<div><span>${esc(m.title)}</span><span>↗</span></div></button>`).join(''):'<p class="empty-state">No matching media. Try another keyword.</p>';$('#load-gallery').hidden=galleryView.length<=galleryLimit;$('#gallery-count').textContent=`${Math.min(galleryLimit,galleryView.length)} of ${galleryView.length} ${galleryView.length===1?'item':'items'}`;}
$('#gallery-search').oninput=()=>{galleryLimit=8;renderGallery();};$('#gallery-type').onchange=()=>{galleryLimit=8;renderGallery();};$('#load-gallery').onclick=()=>{galleryLimit+=12;renderGallery();};
function openMedia(id){const m=byMedia.get(id);if(!m)return;viewer=galleryView.some(x=>x.id===id)?galleryView:media;viewerIndex=viewer.findIndex(x=>x.id===id);renderMedia();openDialog('media-dialog');}
function renderMedia(){const m=viewer[viewerIndex],isVideo=m.kind==='video',image=$('#media-image'),video=$('#media-video');image.hidden=isVideo;video.hidden=!isVideo;if(isVideo){image.removeAttribute('src');video.src=m.src;video.poster=m.thumb;video.setAttribute('aria-label',m.title);}else{video.removeAttribute('src');video.removeAttribute('poster');image.src=m.src;image.alt=m.title;}$('#media-title').textContent=m.title;$('#media-note').textContent=isVideo?'Supplied product video · Use playback controls':'Original artwork · Use your browser to zoom';$('#media-download').href=m.src;$('#media-download').download=m.id+(isVideo?'.mp4':'.webp');$('#media-download').textContent=isVideo?'Download video ↓':'Download image ↓';$('#media-products').innerHTML=(m.products||[]).filter(id=>byId.has(id)).map(id=>`<button class="button dark" data-product="${id}">${esc(byId.get(id).name)} ↗</button>`).join('');}
$('#media-prev').onclick=()=>{viewerIndex=(viewerIndex-1+viewer.length)%viewer.length;renderMedia();};$('#media-next').onclick=()=>{viewerIndex=(viewerIndex+1)%viewer.length;renderMedia();};
document.addEventListener('keydown',e=>{if(!$('#media-dialog').open)return;if(e.key==='ArrowLeft')$('#media-prev').click();if(e.key==='ArrowRight')$('#media-next').click();});
document.addEventListener('change',e=>{const el=e.target;if(el.dataset.compare){const id=el.dataset.compare;if(el.checked){if(compare.length===3){el.checked=false;toast('Compare up to three laptops at a time.');return;}compare.push(id);}else compare=compare.filter(x=>x!==id);updateCompare();}});
document.addEventListener('click',e=>{const btn=e.target.closest('[data-category],[data-product],[data-enquire],[data-save],[data-add],[data-close],[data-reset],[data-remove],[data-quantity],[data-media],[data-detail-photo]');if(!btn)return;const d=btn.dataset;
 if(d.category){state.category=d.category;state.saved=false;state.limit=12;renderProducts();$('#shop').scrollIntoView({behavior:'smooth'});}
 if(d.product){if($('#media-dialog').open)$('#media-dialog').close();openProduct(d.product);}
 if(d.save){saved=saved.includes(d.save)?saved.filter(x=>x!==d.save):[...saved,d.save];persist('saved',saved);renderProducts();if($('#product-dialog').open&&currentProduct===d.save){btn.textContent=saved.includes(d.save)?'♥ Saved':'♡ Save for later';}toast(saved.includes(d.save)?'Saved to your favourites':'Removed from favourites');}
 if(d.enquire)startEnquiry(d.enquire,d.selected==='true');
 if(d.add)addBag(d.add,currentProduct===d.add?currentVariant:0);
 if(d.close)$('#'+d.close)?.close();
 if('reset' in d)reset();
 if('remove' in d){bag.splice(Number(d.remove),1);renderBag();}
 if('quantity' in d){const item=bag[Number(d.quantity)];if(item){const qty=item.qty+Number(d.change);if(qty>10)toast('For bulk enquiries, please contact Apex Computers.');else if(qty<1)bag.splice(Number(d.quantity),1);else item.qty=qty;renderBag();}}
 if(d.media)openMedia(d.media);
 if(d.detailPhoto){const m=byMedia.get(d.detailPhoto);if(m){$('#detail-player').innerHTML=detailMedia(m);$('#detail-caption').textContent=mediaCaption(m);}}
});
// Reset success controls when a later enquiry bag is opened.
$('#bag-dialog').addEventListener('close',()=>{if(bag.length){$('#send-enquiry').hidden=false;$('#bag-whatsapp').hidden=false;$('#bag-sms').hidden=false;}});
$('#media-dialog').addEventListener('close',()=>{$('#media-video').removeAttribute('src');});
function readProductLink(){const params=new URLSearchParams(location.hash.slice(1));if(params.has('product'))openProduct(params.get('product'),Number(params.get('variant')||0));if(params.has('bag'))openBag();}
addEventListener('hashchange',readProductLink);
document.addEventListener('languagechange',()=>{
 renderProducts();updateGeneralContacts();
 if($('#product-dialog').open&&currentProduct)renderProduct();
 if(bag.length)renderBag();
 if($('#compare-dialog').open)$('#compare-open').onclick();
 // Search again using both language aliases without clearing the customer's inputs.
 renderGallery();showEmailAvailability();
});
syncBag();renderProducts();renderGallery();updateCompare();readProductLink();updateGeneralContacts();
})();
